### ISSUE TITLE
Extra tags

### ISSUE THREAD

**Issue by Kaaimann** [andrew-pickin/nagios2influx#1]
Hi Andrew,

Just wondering if there is any possibility to add a extra tag label to the influx string

Wkr,

Kris

**Comment by andrew-pickin** [comment]
I don't actually use this any more so I can't actually guarantee the follow as tested. 

But to add an additional tag it should require changes to the code (it already supports multiple tags) only changes to your config.
So in `commands.cfg` add the field you want to be written into the new tag in the `printf`, then and `tag=<newtag>` in `nagios2influx.cfg`. For example to change `$SERVICESTATE$` from being ignored (eg. void) replace the `void` with `tag=service_state`. 

Hopefully.
